### ISSUE TITLE
排版 代码块混乱

### ISSUE THREAD

**Issue by fanleikong** [doocs/md#1]
![image](https://user-images.githubusercontent.com/42208737/70366113-071fa500-18d0-11ea-8a40-33add2fa3e69.png)

**Comment by yanglbme** [comment]
@fanleikong 你好，我这边测试是没有问题的。

![image](https://user-images.githubusercontent.com/21008209/70367013-1b1ad500-18d7-11ea-87c8-ec05349efda3.png)

你可以在单行引用与下方代码块**以空行隔开**试试，也推荐你使用 Chrome 浏览器，Chrome 支持窗口同步滚动，样式也更好。

![image](https://user-images.githubusercontent.com/21008209/70367076-a7c59300-18d7-11ea-9968-d00ac2489e7a.png)

**Comment by fanleikong** [comment]
好的，谢谢，我用的edge浏览器，空格试过无效，等一月份Edge换成谷歌内核应该就可以了，就不下谷歌了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yang Libin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月7日(星期六) 上午9:55
收件人:&nbsp;"doocs/md"<md@noreply.github.com&gt;;
抄送:&nbsp;"孔凡雷"<3375024578@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [doocs/md] 排版 代码块混乱 (#1)




@fanleikong 你好，我这边测试是没有问题的。
 

 
你可以在单行引用与下方代码块以空行隔开试试，也推荐你使用 Chrome 浏览器，Chrome 支持窗口同步滚动，样式也更好。
