### ISSUE TITLE
图片上传失败

### ISSUE THREAD

**Issue by qidian360** [doocs/md#10]
请问github搭建的图床粘贴时会报:图片上传失败。示例中的可以正常粘贴。为什么？

**Comment by yanglbme** [comment]
@qidian360 你好，图片从哪里上传？上传到哪里？麻烦详细说一下，谢谢。

**Comment by qidian360** [comment]
@yanglbme 您好，
1. 图片是github+PicGo搭建的图床中的图片，例如![](https://raw.githubusercontent.com/qidian360/oss/master/img/%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%90%86.png );
2. 本地markdown编辑时，插入上述图片，将渲染后的页面复制粘贴在微信公众号的富文本编辑框，粘贴后会有提示:图片上传失败；
3. 图壳中的图片做同样的操作，微信富文本编辑框无报错

**Comment by yanglbme** [comment]
@qidian360 
GitHub 使用的是美国的服务器，你资源存放在上面，在 markdown 中引用链接，然后渲染图文复制到公众号，图片上传失败是正常的。

你不妨使用国内的 Git 服务 [Gitee](https://gitee.com) 作静态资源托管，正常来说是能成功的。

- 示例仓库：https://gitee.com/yanglbme/resource
- 图片位置：/images/back.jpg
- 引用链接：https://gitee.com/yanglbme/resource/raw/master/images/back.jpg

我在 [doocs/md 编辑器](https://doocs.gitee.io/md) 使用语法 `![](https://gitee.com/yanglbme/resource/raw/master/images/back.jpg)` 复制到公众号，正常显示。

![](https://gitee.com/yanglbme/resource/raw/master/images/back.jpg)

**Comment by qidian360** [comment]
@yanglbme 非常感谢
