### ISSUE TITLE
编辑器外观重构

### ISSUE THREAD

**Issue by yanglbme** [doocs/md#102]
编辑器可能要在外观上做调整，将顶部菜单栏调整为软件菜单栏的形式，大致分为：

| 文件                                | 格式                                                                     | 编辑                 | 样式                                 | 帮助 |
| ----------------------------------- | ------------------------------------------------------------------------ | -------------------- | ------------------------------------ | ---- |
| 导入 .md<br> 导出 .md<br>导出 .html<br>设置偏好(黑夜模式等) | 加粗<br>斜体<br>删除线<br>超链接<br>格式化<br>微信外链转底部引用<br>重置 | 插入图片<br>插入表格 | 字体<br>字号<br>主题色<br>自定义 CSS | 关于 |

有没有同学有兴趣做的？或者有没有其他更好的设计实现方案，欢迎交流

**Comment by wll8** [comment]
我建议把所有设置的东西都放在那个齿轮按钮里去，登录设置上传方式，就是属于设置。但是现在是点击那个齿轮就只直接弹出个 css。

类似于:
- 设置
  - 样式
  - 上传

**Comment by yanglbme** [comment]
@wll8 这个可以

**Comment by yanglbme** [comment]
@wll8 那设置里，样式应该包含 字体、字号、主题色等等这些？

**Comment by wll8** [comment]
感觉可以的。统一收纳。毕竟 `字体、字号、主题色` 这些应该不常用，每个公众号有自己的风格，选择好了就不经常变了。

但是一些编辑辅助功能是常用的，例如调整某些文字的样式、快捷插入某些内容啥啥的。

**Comment by ZhaoUncle** [comment]
可以参考一下这个开源设计，目前看了下很多方面要是能合并在一起，就堪称功能翻倍了，技术栈也比较类似，可作参考。特备是图片上传的，这个项目是 ok 的

**Comment by wll8** [comment]
@ZhaoUncle 
目前通过该插件暴露的 API 实现了编辑的文章直接发布。
![Video_2022-02-28_111811](https://user-images.githubusercontent.com/28223260/155919158-f08b338f-f2b4-41c3-8bf2-91cdf34fba70.gif)

对于你说的合并，是不能完成的。因为它是一个浏览器插件，可以获取到很多权限，例如用户信息、跨域。但 doocs/md 这个项目是单纯的前端项目，是得不到这些权限的。如果非要支持，只能把 doocs/md 也做成插件，或者在他的插件里集成 doocs/md 。
