### ISSUE TITLE
代码块复制问题

### ISSUE THREAD

**Issue by miaogaolin** [doocs/md#103]
复制后的代码粘贴到公众号没有背景色：
![image](https://user-images.githubusercontent.com/57740293/143528224-27392965-6235-4608-9b7e-6d84ed4747f5.png)

https://doocs.github.io/md/ 在线编辑器中是这个样子：
![image](https://user-images.githubusercontent.com/57740293/143528271-98b28ef9-b124-4367-957c-335dbd3f6bb0.png)

**Comment by yanglbme** [comment]
在代码块前后加文字，复制应该可以
