### ISSUE TITLE
本地启动失败

### ISSUE THREAD

**Issue by Weilet** [doocs/md#126]
系统：macOS 12
node 版本： 14.15.5
使用了 nvm，错误截图如下：
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/32561597/153624309-5fa86364-445c-4a46-a364-3ec9e38dbd92.png">

**Comment by wll8** [comment]
收到，将在今天处理。

**Comment by wll8** [comment]
感谢反馈，我使用 ubantu 重现了这个问题。目前 md-cli v0.0.4 版本已修复，可以尝试一下是否已经解决此问题。

这是 linux 上的成功使用截图:
![image](https://user-images.githubusercontent.com/28223260/153712065-e73169ae-4b25-4123-be9a-9bef748d517a.png)


这是 win10 上的成功使用截图:
![image](https://user-images.githubusercontent.com/28223260/153712177-fd33615f-3c49-48b2-b927-f2dc94cf59b7.png)

**Comment by Weilet** [comment]
更新后问题修复，issue 关闭了
