### ISSUE TITLE
请求 Github Pages 的 CNAME支持

### ISSUE THREAD

**Issue by viticis** [doocs/md#132]
看到该项目提交代码后会通过Github Action部署到Github Pages.

可以使用 `{user}.github.io/md`域名去访问.

如果在gh-pages手动添加CNAME文件，由于Github部署时候带了子目录`md`，而CNAME是在根目录，会导致全部文件404.

并且，每次提交都会重新部署一次，似乎会导致gh-pages分支的CNAME文件丢失.

能否添加完善的CNAME支持，可以使用自定义域名访问，感谢.

**Comment by wll8** [comment]
项目支持根目录部署。部署方式命令为: `npm run build:h5-netlify`

**Comment by viticis** [comment]
> 项目支持根目录部署。部署方式命令为: `npm run build:h5-netlify` . 例: https://mdhere.netlify.app/

是的，我看到了，这里我可以自行修改fork后的github action的yml文件.

但是，如何能够配置后，每次部署 CNAME 都生成到gh-pages分支呢？（类似hugo之类的静态博客）.

**Comment by wll8** [comment]
感觉可以扩展为在 github action 中添加 `生成到gh-pages分支` 的 git 操作, 可能会有使用 sh 创建 gh-pages 分支, 提交 dist 到此分支啥啥的, 不过具体没弄过, 待会管理员来看看.

**Comment by yanglbme** [comment]
看这里有没有满足你的需求，可以自行配置：https://github.com/JamesIves/github-pages-deploy-action#additional-build-files-

![image](https://user-images.githubusercontent.com/21008209/153787748-a19b9c6f-6889-40f5-a20e-8f99861288bb.png)

**Comment by viticis** [comment]
> 看这里有没有满足你的需求，可以自行配置：https://github.com/JamesIves/github-pages-deploy-action#additional-build-files-
> 
> ![image](https://user-images.githubusercontent.com/21008209/153787748-a19b9c6f-6889-40f5-a20e-8f99861288bb.png)

原意是想从代码层面解决，并且可以作为feature，其他人需要的话也可以直接配置CNAME了.
不过两位这么一提醒，我发觉我自己用的话，还是直接用github action直接echo到dist目录里好了.
感谢.
