### ISSUE TITLE
关于公众号右侧文字对齐的问题

### ISSUE THREAD

**Issue by RalstonLiu** [doocs/md#152]
作者您好！非常惊喜能看到这么一款Markdown的微信公众号的编辑器，非常喜欢。

不过我在使用中也发现了一些小问题，就是我们的编辑器复制到公众号后，右侧似乎对齐不了，

![](https://img.laoda.de/i/2022/05/16/xw5xf7-0.webp)

![](https://img.laoda.de/i/2022/05/16/xwo2a1-0.webp)

(我手机是iPhone13 mini，一开始以为是自己手机的问题，然后我又尝试用另一个款[类似的编辑器](https://markdown.com.cn/editor/)的时候，没有这个问题)

![](https://img.laoda.de/i/2022/05/16/xxr1ud-0.webp)

上图这个是用https://markdown.com.cn/editor/ 这个编辑器的效果。

不知道是否支持自己设置右边也能对齐呢？感觉看起来会舒服一些。

以上。

再次感谢有这么一款好用的编辑器！

**Comment by yanglbme** [comment]
右侧自定义 CSS，可以调整段落样式，比如：

```css
/* 段落样式 */
p {
  text-align:justify
}
```

**Comment by RalstonLiu** [comment]
> 右侧自定义 CSS，可以调整段落样式，比如：
> 
> ```css
> /* 段落样式 */
> p {
>   text-align:justify
> }
> ```

非常感谢！
