### ISSUE TITLE
主题添加

### ISSUE THREAD

**Issue by Ran-Xing** [doocs/md#168]
大佬你好，能否把这个代码块的 mac 风格复制一下

https://editor.mdnice.com/

**Comment by Ran-Xing** [comment]
这就很尴尬
url + 二级标题
![image](https://user-images.githubusercontent.com/73819467/182645421-84fcc1e7-4077-45af-abd5-07972350010e.png)

**Comment by yanglbme** [comment]
这个我们看看

**Comment by zhouyupeng** [comment]
> 大佬你好，能否把这个代码块的 mac 风格复制一下
> 
> https://editor.mdnice.com/

确实，这个网站的很好用，用了很久了，不知道能不能集成一些进来。
