### ISSUE TITLE
请问如何修改示例里的图片链接

### ISSUE THREAD

**Issue by huhexian** [doocs/md#173]
这是我用docker部署的：https://md.huhexian.cn

示例里的图片大部分是gitee的，在预览中显示不出来，请问如何修改示例的图片链接呢？

**Comment by wll8** [comment]
- 如果你是要修改示例 markdown 中的图片地址, 请修改[此文件](https://github.com/doocs/md/blob/main/src/assets/example/markdown.md)
- gitee 已经不允许外链
- 自定义上传地址, 可以参考 [自定义上传逻辑](https://github.com/doocs/md#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8A%E4%BC%A0%E9%80%BB%E8%BE%91)

**Comment by yanglbme** [comment]
Docker 镜像已更新至最新，新版已移除 Gitee 图片，可以重新执行 `docker pull doocs/md:latest` 获取最新镜像 @huhexian

**Comment by huhexian** [comment]
@yanglbme @wll8  谢谢
