### ISSUE TITLE
可以给某个词单独设置字号和颜色吗？

### ISSUE THREAD

**Issue by jjeejj** [doocs/md#18]
在写文章的时候，有时候想强调某句话 需要改变颜色和字号，现在有办法做到吗？ 

我看现有的编辑页面，显示的字号和颜色设置是针对全文的
![image](https://user-images.githubusercontent.com/15176971/84996621-16858200-b180-11ea-8ae7-d8551cc7bc13.png)

**Comment by yanglbme** [comment]
可以自己加一些简单的css样式，比如：

![image](https://user-images.githubusercontent.com/21008209/84997456-34071b80-b181-11ea-8557-d04ecf78648b.png)

**Comment by jjeejj** [comment]
解决了 👍
