### ISSUE TITLE
复制到公众号上粘贴并没有展现出样式

### ISSUE THREAD

**Issue by Yapwn** [doocs/md#188]
使用的浏览器：Edge Version 104.0.1293.54 (Official build) (x86_64)
浏览器插件：全部关掉也尝试过
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/49093992/185776219-04a90e06-04c6-48df-81ff-c04f0f2a5141.png">

**Comment by yanglbme** [comment]
![image](https://user-images.githubusercontent.com/21008209/185786750-292ec3b9-e883-4d39-bfd9-ec4ef13cf444.png)

我这边用 Edge，是正常的，没有复现你描述的情况。

**Comment by yanglbme** [comment]
有提供导出 .html 的功能

**Comment by jonnywang** [comment]
> 有提供导出 .html 的功能

官网的复制按钮的确让我迷惑了一下，  请问md提供组件化吗？

**Comment by yanglbme** [comment]
复制到富文本编辑器才行。组件化目前没有哈

**Comment by Yapwn** [comment]
解决了，那天可能是电脑不知道咋了，间歇性抽风，休息一晚上就好了！
