### ISSUE TITLE
Safari 无法打开网站

### ISSUE THREAD

**Issue by juemuren4449** [doocs/md#196]
Mac 版本：12.6
Safari 版本：16.0
Safari 打开 https://doocs.gitee.io/md/ 或者 https://doocs.github.io/md/ 页面都是空白，控制台报错 `SyntaxError: Invalid regular expression: invalid group specifier name`
<img width="964" alt="image" src="https://user-images.githubusercontent.com/12666694/198630373-c363e00e-e90f-47fb-aef6-e46c5d86b069.png">

**Comment by axiaoxin** [comment]
+1
