### ISSUE TITLE
斜体显示

### ISSUE THREAD

**Issue by SiweiShen2019** [doocs/md#20]
我注意到本项目（我pull了最新的代码在本地也测试过）使用`*斜体*`显示会导致换行，不知道是否故意这么设计的？

![md](https://user-images.githubusercontent.com/17442826/85215330-ace8bc00-b3a9-11ea-9dab-99c5986b290e.jpg)

另外，我最近才发现使用这个项目，对会一些技术的人来说真的很友好！谢谢你的贡献！

**Comment by yanglbme** [comment]
@SiweiShen2019 谢谢反馈，我们会尽快处理

**Comment by yanglbme** [comment]
已修复
