### ISSUE TITLE
Vercel 项目完成后域名打开空白

### ISSUE THREAD

**Issue by noaai** [doocs/md#225]
Vercel 项目完成后，通过访问自带域名或自己域名打开后是空白页面。Build Logs: https://md-1r8s3hgf6-noaai.vercel.app/
![vercel wechat](https://github.com/doocs/md/assets/134377153/f705b9f9-630c-413e-af09-8db6cd6e492d)

**Comment by yanglbme** [comment]
我们有两种部署的方式：

```sh
# 部署在 /md 目录
npm run build
# 访问 http://127.0.0.1:9000/md

# 部署在根目录
npm run build:h5-netlify
# 访问 http://127.0.0.1:9000/
```

部署在根目录，请使用 `npm run build:h5-netlify`
