### ISSUE TITLE
公众号 LaTeX 渲染异常

### ISSUE THREAD

**Issue by YangFong** [doocs/md#254]
已知：部分在站点渲染出来的效果，和复制到公众号当中的表现不一。

测试用例

```md
$$
f(x)=\left\{
\begin{aligned}
x & = & \cos(t) \\
y & = & \sin(t) \\
z & = & \frac xy
\end{aligned}
\right.
$$
```

![image](https://github.com/doocs/md/assets/70502828/c482d35c-9a2f-4a7a-860b-6228c92facb1)

**Comment by HananxR** [comment]
行内公式($公式$)和行间公式($$公式$$)好像无法识别

**Comment by YangFong** [comment]
@HananxR 需要提供复现步骤。

**Comment by HananxR** [comment]
示例：如下，目前好像不生效
![公式问题](https://github.com/doocs/md/assets/32954669/d69a5294-8b42-4637-8a32-dd4a2cc13f65)

**Comment by YangFong** [comment]
> 示例：如下，目前好像不生效. ![公式问题](https://user-images.githubusercontent.com/32954669/282734956-d69a5294-8b42-4637-8a32-dd4a2cc13f65.png)

需要在其前方添加一个空格：

<img width="797" alt="image" src="https://github.com/doocs/md/assets/70502828/b3157c07-75ec-4f0f-b709-42fcf672a7c7">

我知道这和一些编辑器的规则不同，但其渲染机制就是如此。

**Comment by yanglbme** [comment]
GitHub 在渲染 Latex 公式也类似，需要打空格才行：

不打空格的效果：

时间复杂度$O(n)$，空间复杂度$O(n)$。其中$n$是数组$nums$的长度。

打空格的效果：

时间复杂度 $O(n)$，空间复杂度 $O(n)$。其中 $n$ 是数组 $nums$ 的长度。

**Comment by HananxR** [comment]
> > 示例：如下，目前好像不生效. ![公式问题](https://user-images.githubusercontent.com/32954669/282734956-d69a5294-8b42-4637-8a32-dd4a2cc13f65.png)
> 
> 需要在其前方添加一个空格：
> 
> <img alt="image" width="797" src="https://user-images.githubusercontent.com/70502828/282737065-b3157c07-75ec-4f0f-b709-42fcf672a7c7.png">
> 我知道这和一些编辑器的规则不同，但其渲染机制就是如此。

非常感谢，真的有用！感谢感谢!
