### ISSUE TITLE
docker部署后，无法支持公式编辑

### ISSUE THREAD

**Issue by King-Key** [doocs/md#256]
我用docker部署后，编辑的公式似乎无法正常渲染
![image](https://github.com/doocs/md/assets/31676811/710f614c-3197-485a-ae2b-a95e6e74bfce)

**Comment by yanglbme** [comment]
目前最新版尚未发布 docker 镜像

**Comment by King-Key** [comment]
> 目前最新版尚未发布 docker 镜像

了解。那npm的部署方式可以支持公式的问题吗？或者有其他最新版的本地部署方式吗？

**Comment by yanglbme** [comment]
npm 也还没有，目前只有源码仓有公式编辑的最新代码。你可以 clone 到本地，本地跑一个服务？或者直接用我们的在线编辑器 https://doocs.github.io/md

**Comment by King-Key** [comment]
> npm 也还没有，目前只有源码仓有公式编辑的最新代码。你可以 clone 到本地，本地跑一个服务？或者直接用我们的在线编辑器 https://doocs.github.io/md

了解，感谢🙏

**Comment by yanglbme** [comment]
可以拉一下最新 docker 镜像试试，我刚刚发布了最新版本了 @King-Key

**Comment by King-Key** [comment]
好的好的，感谢🙏发自我的 iPhone在 2023年12月5日，19:40，Libin YANG ***@***.***> 写道：﻿
可以拉一下最新 docker 镜像试试，我刚刚发布了最新版本了 @King-Key
