### ISSUE TITLE
数学公式展示不正常

### ISSUE THREAD

**Issue by huifer** [doocs/md#265]
内切圆是一个与三角形的三条边都相切的圆。设三角形的三边长度分别为 a、b 和 c，对应的三个内角为 $$\angle A$$、$$\angle B$$ 和 $$\angle C$$。

![image](https://github.com/doocs/md/assets/26766909/119c707f-d21d-41cd-be9b-e75026be9f23)

**Comment by yanglbme** [comment]
行内公式用单个 `$` 符号对，然后顿号改用英文逗号。例如：

```txt
内切圆是一个与三角形的三条边都相切的圆。设三角形的三边长度分别为 a、b 和 c，对应的三个内角为 $\angle A$, $\angle B$ 和 $\angle C$。
```

**Comment by yanglbme** [comment]
GitHub 也不支持你上面那种，如果改成我上面的格式，显示效果如下：

内切圆是一个与三角形的三条边都相切的圆。设三角形的三边长度分别为 a、b 和 c，对应的三个内角为 $\angle A$, $\angle B$ 和 $\angle C$。

**Comment by huifer** [comment]
OK, 感谢支持。
