### ISSUE TITLE
gh pages 同步最新版后报错

### ISSUE THREAD

**Issue by komomon** [doocs/md#272]
gh pages 同步最新版后报错，无法渲染

![image](https://github.com/doocs/md/assets/52700174/19cd2fae-027b-40ed-afd0-da300eaee8bd)

**Comment by YangFong** [comment]
能否提供具体的复现步骤，并导致了哪方面不可用

**Comment by komomon** [comment]
最新版测试：对于使用缩进而不是使用```xxx```包裹的代码，会导致报错，从而整篇文章无法渲染，之前的版本不会这样，正常渲染。
整体是只要有一个地方报错，则整片文章无法渲染。

测试md：
```

第一代dex落地壳加固是Android加固的基础，近日学习加固相关知识，记录一下自己踩过的坑和总结自己对落地壳的理解。  
下面的代码或多或少参考了大佬们的代码，主要是加上自己的理解和注释，经过折腾最终在最新版雷电模拟器9（Android9）实现了加固和自解密运行。  
参考项目和文章会放在末尾。


## 1、理论知识

关于DEX文件的组成，可以自行搜索详细学习  
在Android的DEX加固中，主要和DEX头部三个字段有关，分别是：
	
  * checksum  
文件校验码，使用alder32算法校验文件除去maigc，checksum外余下的所有文件区域

  * signature  
使用SHA-1算法hash除去magic、checksum和signature外余下的所有文件区域

  * file_size  
dex文件的大小  
DEX加固主要就是一个拼接  
成品 = 待加固app（会经过加密） + 解密dex  
经过拼接之后，会影响上面说的3个字段，所以需要我们手动去修改更正。


![](https://cuttontail.blog/img/logo.png)

![](https://cuttontail.blog/img/logoa.png)

aaaaa

aaaaa

	
    f, --file            only set one file to be extracted
    -d, --directory       set a directory to be extracted
    -D, --delete          Delete Duplicates 
    -i,--only-ip          only extract IP
    -n,--only-domain      only extract domain name
    -a,--all              extract all, include extract IP and extract domain name
    -t,--protocol type    matching protocol type, eg:http://127.0.0.1 
    -p,--port             matching port,eg:127.0.0.1:1001
    -h, --help            display this help and exit



bbbbbbb






```
![image](https://github.com/doocs/md/assets/52700174/304c9012-c354-4061-8423-2dcd58805e88)

**Comment by YangFong** [comment]
这是你预期的结果吗

<img width="1013" alt="image" src="https://github.com/doocs/md/assets/70502828/3cd59cc7-7869-4167-97a0-ac38ff1ac670">

**Comment by komomon** [comment]
> 这是你预期的结果吗
> 
> <img alt="image" width="1013" src="https://private-user-images.githubusercontent.com/70502828/306513962-3cd59cc7-7869-4167-97a0-ac38ff1ac670.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTcwMDIsIm5iZiI6MTcwODQ5NjcwMiwicGF0aCI6Ii83MDUwMjgyOC8zMDY1MTM5NjItM2NkNTljYzctNzg2OS00MTY3LTk3YTAtYWMzOGZmMWFjNjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA2MjUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NjZjNTQ1MjA5NmE5MDkyMTY4MDQwNWQ0YTM4ZWFjOGM3ZDFhMzkzMDQ4MTY2NWEyNzRmNjY2MjllN2VkZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HoK9FesnxtrvMAw_4QksOnp-gfF-D3WxZmLkz3qI_ck">

对，上午刚同步的最新版的console里面爆了很多错，只要有一处错误，什么都渲染不出来，之前并不是，会接着渲染。
