### ISSUE TITLE
Mac 代码块左上角三个图标的显示问题

### ISSUE THREAD

**Issue by joedrm** [doocs/md#285]
PC端浏览器打开微信公众号文章时 Mac 代码块左上角三个图标显示问题，如下图
<img width="691" alt="image" src="https://github.com/doocs/md/assets/7825340/c1161bc1-98c1-4daf-8de3-6f8117ec7941">

**Comment by joedrm** [comment]
> 是否方便提供链接让我看看具体表现

手机上看是没问题的，PC端浏览器上才会出现。

**Comment by YangFong** [comment]
@joedrm OK，感谢提供示例，我查找一下原因。

**Comment by YangFong** [comment]
原因确认了，与PC和移动端无关，而是深色模式下额外带来的样式导致了错乱。

![image](https://github.com/doocs/md/assets/70502828/8ffb8273-fabb-4e43-bd68-237942f4aca7)


![image](https://github.com/doocs/md/assets/70502828/1a91792a-5e6e-49d9-b7cc-444f6a4cdb34)

**Comment by joedrm** [comment]
> 原因确认了，与PC和移动端无关，而是深色模式下额外带来的样式导致了错乱。
> 
> ![image](https://private-user-images.githubusercontent.com/70502828/323989301-8ffb8273-fabb-4e43-bd68-237942f4aca7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Nzg2MTYsIm5iZiI6MTcxMzU3ODMxNiwicGF0aCI6Ii83MDUwMjgyOC8zMjM5ODkzMDEtOGZmYjgyNzMtZmFiYi00ZTQzLWJkNjgtMjM3OTQyZjRhY2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDAxNTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMmIxYWJjNTI3ODhmNjY0NDA0ZWY2NGU4NmQzYTJlZjY1Y2ZhNTc5NWQ4ZTlkYTJmYmU3N2QyZDFiMTgzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lKz5_N8xHyz1TnVjUFKHEULiwJ-WoU_byYAbiqwlGho)
> 
> ![image](https://private-user-images.githubusercontent.com/70502828/323989204-1a91792a-5e6e-49d9-b7cc-444f6a4cdb34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Nzg2MTYsIm5iZiI6MTcxMzU3ODMxNiwicGF0aCI6Ii83MDUwMjgyOC8zMjM5ODkyMDQtMWE5MTc5MmEtNWU2ZS00OWQ5LWI3Y2MtNDQ0ZjZhNGNkYjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDAxNTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZTJmZTZiZWE0OWRlNGEyZjU4NDQ1ZmVkZTE3OTNhY2JhOGM3MzNjZDJhMTFiNzkyODIwMzRmMWZmMDdiY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.peXdMTYm5Z37DOUmasYjOicb-XDNuV5Gmc0SOxNkUhQ)

好的，处理问题效率好高啊，辛苦了辛苦了。
