### ISSUE TITLE
希望支持Markdown图片title变为图注

### ISSUE THREAD

**Issue by Achuan-2** [doocs/md#290]
Markdown 的完整图片语法是 `![anchor text](img_src "title")`
目前语雀、思源笔记都是支持将Markdown图片title变为图注的
anchor text在很多软件里都是会自动生成无意义的“image”文字

**Comment by YangFong** [comment]
提供一个你预期的效果图，我参考一下。

**Comment by Achuan-2** [comment]
只需要wx-renderer.js 把text改为title就好了
![Clip_2024-04-27_17-51-30](https://github.com/doocs/md/assets/60436214/4adc4e49-34b9-4b84-a726-efdac00b0245)
![Clip_2024-04-27_17-51-55](https://github.com/doocs/md/assets/60436214/a3bde268-622d-4fd9-8e27-99fe1e7d46e1)

**Comment by Achuan-2** [comment]
建议还是搞一个选项，图注要么是title要么是anchor text(alt text)，因为很多Markdown软件上传图片，anchor text都默认是文件名（比如Github 就是），所以我只会给需要的图片加上title，显示文件名。
现在这种改进的话，就会导致我所有的图片都有标题，有的显示title，有的显示anchor text。

**Comment by yanglbme** [comment]
你不想加 title 或者 anchor text 的地方，就不加上，它不就没显示了

**Comment by Achuan-2** [comment]
嗯嗯，这不是为了更方便吗，这样就需要每次导出Markdown后一个个改。看大佬愿不愿意改了，我fork了一个repo，让编辑器只渲染title为图注。

**Comment by yanglbme** [comment]
@YangFong 只渲染 title 确实比较合理，我们改一下吧

**Comment by YangFong** [comment]
倒是有一定的场景，我晚上补个版本，加入图注选项，选择渲染模式。

**Comment by Peter-JXL** [comment]
> 倒是有一定的场景，我晚上补个版本，加入图注选项，选择渲染模式。

@YangFong 请问目前有图注选项了吗？我刚用 Docker 部署了下，在设置里好像没看到。

另外，目前好像是将 Alt 文本作为图注...  是否支持将图片文件名作为 Alt 文本？不然每次上传图片后都要手动添加图注，有点点麻烦

**Comment by YangFong** [comment]
> > 倒是有一定的场景，我晚上补个版本，加入图注选项，选择渲染模式。
> 
> [@YangFong](https://github.com/YangFong) 请问目前有图注选项了吗？我刚用 Docker 部署了下，在设置里好像没看到。
> 
> 另外，目前好像是将 Alt 文本作为图注... 是否支持将图片文件名作为 Alt 文本？不然每次上传图片后都要手动添加图注，有点点麻烦

@Peter-JXL 目前倒是没有支持图片名作为图注，选项位置可见：

<img width="1346" height="846" alt="Image" src="https://github.com/user-attachments/assets/5e215d51-847c-4491-b100-9fcd9ae331df" />

我看怎么给你做个适配吧
