### ISSUE TITLE
超过三级的列表复制存在问题

### ISSUE THREAD

**Issue by Achuan-2** [doocs/md#296]
```markdown
# 2024-05-06 10:51:41

* 1

  * 1

    * 1

      * 1

```
使用编辑器渲染后，复制到微信公众号，列表最多只有二级
![Clip_2024-05-06_10-54-11](https://github.com/doocs/md/assets/60436214/091d16dd-9569-4540-8423-55a2faa6ef43)

**Comment by YangFong** [comment]
复现成功，似乎是因为 HTML 组织结构不同的问题，需要实验。

![image](https://github.com/doocs/md/assets/70502828/5e5951fd-6a93-41a2-8716-725f9b01e4e7)

![image](https://github.com/doocs/md/assets/70502828/78a39ac4-c786-4444-996c-22c87ec424de)

**Comment by YangFong** [comment]
对上了，目前的渲染是，次级的列表会包含在 `<li>` 中，而微信则是需要次级列表和 `<li>` 同级。

预期是：

```html
<ul>
	<li></li>
	<ul>
		<li></li>
		<ul></ul>
	</ul>
</ul>
```

目前是：

```html
<ul>
	<li>
		<ul>
			<li>
				<ul></ul>			
			</li>
		</ul>
	</li>
</ul>
```
