### ISSUE TITLE
VERY IMPRESSIVE！

### ISSUE THREAD

**Issue by littlesulley** [doocs/md#3]
VERY IMPRESSIVE and this is the ONLY one i could use in success.
i have one question: do you plan to support LaTex in markdown?

**Comment by yanglbme** [comment]
@littlesulley Thanks for your recognition. I will carefully consider whether to support Latex in the Markdown editor as it may be the needs of a few people.

**Comment by littlesulley** [comment]
thanks for your consideration, looking forward to your update! :)
