### ISSUE TITLE
换行问题

### ISSUE THREAD

**Issue by ting05261** [doocs/md#301]
您好，我在编辑英文单词总是在换行的时候被拆开，
![image](https://github.com/doocs/md/assets/103827840/7b9a6f5f-3420-4486-99e1-404044386f15)

已经添加了自定义的CSS段落如下：
![image](https://github.com/doocs/md/assets/103827840/8d53e7da-ac73-423b-bc08-07556577f729)

请问一下有什么好的办法么

感谢！

**Comment by YangFong** [comment]
@ting05261 这个问题确实存在，你可以加入这样的 css：

```css
p {
  word-break: initial;
}
```

会得到这样的结果：

<img width="1617" alt="image" src="https://github.com/doocs/md/assets/70502828/b44afb41-c7d4-424c-8e29-308b2c9ed435">

**Comment by YangFong** [comment]
这个 issue 等我们来关闭，在它关闭后，你就不需要再加入这段 css 了。

**Comment by ting05261** [comment]
好的！非常感谢！

在 2024年5月25日星期六，YangFong ***@***.***> 写道：
