### ISSUE TITLE
github图床上传图片报错

### ISSUE THREAD

**Issue by ToastandcatV** [doocs/md#304]
github图床上传图片报错404

**Comment by yanglbme** [comment]
目前默认图床暂时不可用，你可以用自己的

**Comment by ToastandcatV** [comment]
> 目前默认图床暂时不可用，你可以用自己的

我用的自己的github图床，但还是会报错"Request failed with status code 404"

**Comment by ToastandcatV** [comment]
> 目前默认图床暂时不可用，你可以用自己的
另外，在本地端能正常显示的图片，在微信公众平台的撰文界面无法正常显示。
