### ISSUE TITLE
在本地端能正常显示的图片复制到微信公众号平台无法正常显示

### ISSUE THREAD

**Issue by ToastandcatV** [doocs/md#305]
在本地端能正常显示的图片复制到微信公众号平台无法正常显示

**Comment by yanglbme** [comment]
你可以利用编辑器，上传到 oss

**Comment by TrumanDu** [comment]
![image](https://github.com/user-attachments/assets/9313842a-e5a9-412d-b060-ba2a141c0f80)
大一点的图片也不能加载

**Comment by YangFong** [comment]
@TrumanDu 方便的话，发一下出现问题的图片，便于测试。

**Comment by TrumanDu** [comment]
@YangFong https://static.trumandu.top/view_good_share.gif 试试这个

**Comment by YangFong** [comment]
@TrumanDu 我的测试结论：

1. 猜测与图片大小有关系，实际不是，更大的图也可以使用
2. 与图片格式无关，其他 Gif 图正常可用
3. 公众号本地上传可用，不是图片非法问题

我尝试使用其他代理转发时碰到了这个：

<img width="792" alt="image" src="https://github.com/user-attachments/assets/2f3ddf71-5c51-4520-b05a-e5c08391326b">

应当是设置了些什么。

**Comment by TrumanDu** [comment]
@YangFong 我又观察了一下log,问题出在公众号edit组件上传image出现问题，只是报错，没有更过错误信息。
