### ISSUE TITLE
vue2 to vue3

### ISSUE THREAD

**Issue by ayu-exorcist** [doocs/md#307]
> Vue 2 已经终止支持且不再维护

花了点时间, 把 `vue-cli4` + `vue2` + `element-ui` 技术架构升级到了 `vite` + `vue3` + `element-plus`, 其他少部分依赖包也手痒跨大版本进行了升级. (代码见: [ayu-exorcist/md](https://github.com/ayu-exorcist/md/tree/develop))

自测后基本流程已经跑通, 但全功能可能仍存在一些依赖包升级后的 API 不兼容等问题. 

由于对功能不够熟悉, 所以希望可以和作者 @yanglbme 一起合作完善剩余的开发功能和测试, 把大部分功能都迁移到最新的依赖包上

**Comment by YangFong** [comment]
休息时间我看看，非必要的依赖，能不升级则不升，主要是先完成从 Vue-cli + V2 到 Vite + V3 的转换。

**Comment by yanglbme** [comment]
https://github.com/doocs/md/tree/dev-vue2-to-vue3

在这个分支上开发哈

**Comment by ayu-exorcist** [comment]
收到

Libin YANG ***@***.***> 于2024年7月1日周一 10:02写道：

**Comment by ZCShou** [comment]
dev-vue2-to-vue3 分支报错 error TS2307: Cannot find module 'node:url' or its corresponding type declarations。需要在 package.json 中添加 `"types": "node"`？

**Comment by YangFong** [comment]
> dev-vue2-to-vue3 分支报错 error TS2307: Cannot find module 'node:url' or its corresponding type declarations。需要在 package.json 中添加 `"types": "node"`？

这是已知问题，需要加入 `@types/node`，预备是放在后面，将组件改为 TS 时更新的，你有需要的话，那我现在先加上吧。

**Comment by ZCShou** [comment]
> > dev-vue2-to-vue3 分支报错 error TS2307: Cannot find module 'node:url' or its corresponding type declarations。需要在 package.json 中添加 `"types": "node"`？
> 
> 这是已知问题，需要加入 `@types/node`，预备是放在后面，将组件改为 TS 时更新的，你有需要的话，那我现在先加上吧。

我在 CSDN 转公众号时发现了这个工具，非常棒！准备学习学习为此项目做点贡献，不过我是搞嵌入式的，得先慢慢学习学习！

**Comment by ZCShou** [comment]
顺便问一下，对于 nodejs 的版本是不是也有限制。比如我最开始用的最新的 20.x（LTS） 版本，发现错误有点多，就换成立 18.x （LTS） 版本

**Comment by YangFong** [comment]
> 顺便问一下，对于 nodejs 的版本是不是也有限制。比如我最开始用的最新的 20.x（LTS） 版本，发现错误有点多，就换成立 18.x （LTS） 版本

有的，当前的 `main` 分支，14 ~ 18 基本都可以，而 `dev-vue2-to-vue3` 则是最低 18+。

预期是兼容 v18 和 v20，确认之后，会补充 `.nvmrc` 示意。
