### ISSUE TITLE
复制到公众号的代码出现缩进异常、及缺少空格的问题

### ISSUE THREAD

**Issue by main-studio** [doocs/md#308]
> 在本地编辑器（Typora）和网页编辑器（[https://doocs.github.io/md/）显示都是正常的，从网页编辑器复制公众号出现上述问题。
> 
> 使用浏览器：Chrome
> 
> 公众号显示：
>
> <img alt="公众号" width="547" src="https://private-user-images.githubusercontent.com/117972021/345458459-5bcf01eb-b1db-4097-b679-7318d157a111.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTY1ODksIm5iZiI6MTcyMDAxNjI4OSwicGF0aCI6Ii8xMTc5NzIwMjEvMzQ1NDU4NDU5LTViY2YwMWViLWIxZGItNDA5Ny1iNjc5LTczMThkMTU3YTExMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNDE4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGJjOGI1OTkyMGQ5ODM2YjJmYmY2ZGFiNWY5YTcxYzM2MDEyYTg2YjUyMjg2ZGVmOTUxZTA3YmI1ZjY3MjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O0YwKTDOxinoKqYiPeZQL4FMCvuiraMH-slpbF7mJ9w"> 
>
> 网页编辑器显示：
>
> <img alt="网页编辑器" width="546" src="https://private-user-images.githubusercontent.com/117972021/345458490-da8592e6-cca9-427a-b125-e71d769926ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTY1ODksIm5iZiI6MTcyMDAxNjI4OSwicGF0aCI6Ii8xMTc5NzIwMjEvMzQ1NDU4NDkwLWRhODU5MmU2LWNjYTktNDI3YS1iMTI1LWU3MWQ3Njk5MjZlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNDE4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTJkN2EwZDUxZjU2NWQ3MDkzMGRhZTA0ZDI1M2JhMmFhNmVkMTU0ZmZlZGFlMWU5ZjQxYzBjOGRiZGQ0NTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OfstTmpfJGKjIbGO-JGPmAvU7PJymDNpfMEA5K8SLEk">

**Comment by main-studio** [comment]
> 在本地编辑器（Typora）和网页编辑器（[https://doocs.github.io/md/）显示都是正常的，从网页编辑器复制公众号出现上述问题。
> 
> 使用浏览器：Chrome
> 
> 公众号显示：
>
> <img alt="公众号" width="547" src="https://private-user-images.githubusercontent.com/117972021/345458459-5bcf01eb-b1db-4097-b679-7318d157a111.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTY1ODksIm5iZiI6MTcyMDAxNjI4OSwicGF0aCI6Ii8xMTc5NzIwMjEvMzQ1NDU4NDU5LTViY2YwMWViLWIxZGItNDA5Ny1iNjc5LTczMThkMTU3YTExMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNDE4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGJjOGI1OTkyMGQ5ODM2YjJmYmY2ZGFiNWY5YTcxYzM2MDEyYTg2YjUyMjg2ZGVmOTUxZTA3YmI1ZjY3MjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O0YwKTDOxinoKqYiPeZQL4FMCvuiraMH-slpbF7mJ9w"> 
>
> 网页编辑器显示：
>
<img alt="网页编辑器" width="546" src="https://private-user-images.githubusercontent.com/117972021/345458490-da8592e6-cca9-427a-b125-e71d769926ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTY1ODksIm5iZiI6MTcyMDAxNjI4OSwicGF0aCI6Ii8xMTc5NzIwMjEvMzQ1NDU4NDkwLWRhODU5MmU2LWNjYTktNDI3YS1iMTI1LWU3MWQ3Njk5MjZlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNDE4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTJkN2EwZDUxZjU2NWQ3MDkzMGRhZTA0ZDI1M2JhMmFhNmVkMTU0ZmZlZGFlMWU5ZjQxYzBjOGRiZGQ0NTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OfstTmpfJGKjIbGO-JGPmAvU7PJymDNpfMEA5K8SLEk">

**Comment by YangFong** [comment]
麻烦提供一下出现异常的文本内容，我这边未能复现成功。

**Comment by main-studio** [comment]
【实例】

```c
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

void set_seed(void);
char generate_random_character(void);
void generate_random_string(char* receive_string,unsigned int string_length);

int main(void)
{
    unsigned int password_length = 4;
    char password_buffer[password_length + 1]; // +1 用来存储字符串结尾的转译字符 '\0'

    set_seed();	// 设置 rand() 函数的种子
    generate_random_string(password_buffer,password_length); // 生成随机字符串

    printf("%s",password_buffer);

    return 0;
}
```

**Comment by YangFong** [comment]
复现成功，但是还没法给出解释，需要等待排查。

**Comment by main-studio** [comment]
好的，麻烦你啦😄

**Comment by yanglbme** [comment]
@main-studio 应该修复了，可以再试试看

**Comment by yanglbme** [comment]
有问题再反馈
