### ISSUE TITLE
腾讯云cos无法使用

### ISSUE THREAD

**Issue by ShixiangWang** [doocs/md#314]
想请教下，是配置有什么问题么？

<img width="654" alt="image" src="https://github.com/user-attachments/assets/16b78c34-1c20-48f1-bac9-720e31726980">

<img width="670" alt="image" src="https://github.com/user-attachments/assets/498b8b69-1a5d-471a-93f9-e3fbb723b546">

<img width="1239" alt="image" src="https://github.com/user-attachments/assets/7763fc70-86a6-4b72-a5d2-fc9286ee5d83">

**Comment by yanglbme** [comment]
我试了没问题，你配一下跨域访问试试：

![image](https://github.com/user-attachments/assets/0ca657e1-368d-4e59-b339-dc7f0ffd8e77)

![image](https://github.com/user-attachments/assets/796abc2d-383c-4864-ba76-5ff99bd2b0c5)
