### ISSUE TITLE
切换颜色后标题字号改变

### ISSUE THREAD

**Issue by hzs2589** [doocs/md#315]
在`样式 -> 颜色`中切换颜色后，一二三级标题的字体会变小，变得与正文的字号相同。刷新网页后标题字号恢复，再次在`样式 -> 颜色`中切换颜色，标题字号仍会变小。

初始样式：
![image](https://github.com/user-attachments/assets/a1eedab1-d2df-4d8d-91ff-62da460d5268)

修改颜色后：
![image](https://github.com/user-attachments/assets/52a3d4d2-9286-4024-88b1-39ba4f2acf64)

复现视频gif：
![Screen-Recording-2024-07-23-at-15 09 45](https://github.com/user-attachments/assets/f40c2119-015c-4cf5-9578-b0ad3b9be932)

MacOS 14.4.1 
Chrome Version 126.0.6478.183 (Official Build) (arm64)

**Comment by YangFong** [comment]
情况属实，在修改颜色的同时，会更新 h1 ~ h4 的 `size`，然而这修改与初始化的样式有些不一致，需要等我统一这两端的样式。
