### ISSUE TITLE
如果想自建模板样式，就需要在自己服务器搭建吗？

### ISSUE THREAD

**Issue by 37duer** [doocs/md#318]
如果想自建模板样式，就需要在自己服务器搭建吗？

**Comment by YangFong** [comment]
若是你说的模版样式，是指自定义 CSS 样式，站点是有的。

**Comment by 37duer** [comment]
> 若是你说的模版样式，是指自定义 CSS 样式，站点是有的。

嗯，差不多那个意思，我是想在现有模板基础上做一些调整，然后存成我自己的样式模板，下次直接用，当然这里面肯定是要改CSS的，刚刚用了MDnice，无法复制到公众号上，看了推荐来doocs平台，确实简洁好用，我没有太多需要，就是定期在公众号发招聘信息，所以只要一个固定模板就行，感谢作者制作这么好的平台

**Comment by YangFong** [comment]
如果你只有一套固定的模版，我想当前版本是可以满足需求你的需求的，站点会使用浏览器缓存保存编辑区内容和自定义样式。

要是你有多套模版和样式，那就需要自已存储到其他地方（如文件），需要时再手动复制使用了。

后续也有计划，支持多套自义定。

**Comment by 37duer** [comment]
> 如果你只有一套固定的模版，我想当前版本是可以满足需求你的需求的，站点会使用浏览器缓存保存编辑区内容和自定义样式。
> 
> 要是你有多套模版和样式，那就需要自已存储到其他地方（如文件），需要时再手动复制使用了。
> 
> 后续也有计划，支持多套自义定。

谢谢，我只有一套，我以为不会缓存保存
