### ISSUE TITLE
[toc] 支持

### ISSUE THREAD

**Issue by zhangshenghang** [doocs/md#320]
支持 [toc] 自动生成目录，这个可以实现吗

**Comment by YangFong** [comment]
可以实现，但该项目主要是为了公众号发文格式化，不会用到这个。有这个需求，你可以自己 fork 修改。

**Comment by zhangshenghang** [comment]
> 可以实现，但该项目主要是为了公众号发文格式化，不会用到这个。有这个需求，你可以自己 fork 修改。

了解
