### ISSUE TITLE
超链接转换到公众号后，预览不能点击不能调整

### ISSUE THREAD

**Issue by jc0803kevin** [doocs/md#321]

**Comment by YangFong** [comment]
公众号发文的链接，只允许对标公众号文章：

<img width="941" alt="image" src="https://github.com/user-attachments/assets/69bfe639-07c4-4a18-82df-73073f75d231">

其他链接需要明文展示，或开启底部引用：

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/4129fd72-cdba-42b3-ac71-b7215809597e">
