### ISSUE TITLE
支持公式前后不加空格

### ISSUE THREAD

**Issue by LucidaLu** [doocs/md#323]
使用过程中，发现：
1. `$\alpha$ -approximation` $\alpha$ -approximation：可以渲染
2. `$\alpha$-approximation` $\alpha$-approximation：无法正常渲染

希望能使得第二种可以正常渲染，因为第一种渲染出来之后会多一个空格。魔改渲染引擎应该可以解决？

感谢作者！非常棒的项目！

**Comment by yanglbme** [comment]
Hi @LucidaLu 

我改了，目前支持公式前后不加空格

**Comment by LucidaLu** [comment]
神速！感谢！
