### ISSUE TITLE
求教这个怎么部署到web服务器？

### ISSUE THREAD

**Issue by star2k** [doocs/md#36]
请问这个怎么部署到web服务器，求使用教程？

**Comment by yanglbme** [comment]
@star2k 大致步骤如下：

1. 在服务器上安装 node 环境；
1. 克隆本项目到服务器：`git clone git@github.com:doocs/md.git`；
1. 项目目录下运行：`npm install`；
1. 运行打包：`npm run build`；
1. dist 文件夹即为打包后的代码；
1. 搭建 http 服务，部署包文件。

**Comment by star2k** [comment]
> 
> 
> @star2k 大致步骤如下：
> 
>     1. 在服务器上安装 node 环境；
> 
>     2. 克隆本项目到服务器：`git clone git@github.com:doocs/md.git`；
> 
>     3. 项目目录下运行：`npm install`；
> 
>     4. 运行打包：`npm run build`；
> 
>     5. dist 文件夹即为打包后的代码；
> 
>     6. 搭建 http 服务，部署包文件。

谢谢，下次尝试学习一下。这会儿能分享一份打包后的代码么？

**Comment by yanglbme** [comment]
https://github.com/doocs/md/tree/gh-pages 这个分支就是打包后的

**Comment by star2k** [comment]
> 
> 
> https://github.com/doocs/md/tree/gh-pages 这个分支就是打包后的

太感谢了，
![Uploading 图片.png…]()

**Comment by shenweiyan** [comment]
直接用 https://github.com/doocs/md/tree/gh-pages 这个分支部署 github pages，404 无法访问？

**Comment by yanglbme** [comment]
> 直接用 https://github.com/doocs/md/tree/gh-pages 这个分支部署 github pages，404 无法访问？
> 
> 需要在 url 后面加一个 "index.html#/" 就可以了~

嗯嗯，好的

**Comment by shenweiyan** [comment]
请教一下，gh-pages 这个分支的 index.html 不能直接在浏览器打开么？我在 Chrome 直接打开是空白的，没有内容。

**Comment by yanglbme** [comment]
> 请教一下，gh-pages 这个分支的 index.html 不能直接在浏览器打开么？我在 Chrome 直接打开是空白的，没有内容。

需要有 http 服务才行

**Comment by shenweiyan** [comment]
> > 请教一下，gh-pages 这个分支的 index.html 不能直接在浏览器打开么？我在 Chrome 直接打开是空白的，没有内容。
> 
> 需要有 http 服务才行

ok，感谢！
