### ISSUE TITLE
公式在安卓和IOS上显示的不一样

### ISSUE THREAD

**Issue by cangfengzhs** [doocs/md#376]
Markdown
```
  $$ y =f_{\pmb{w}}(\pmb{x})= \sum_{i=1}^mw_ix_i  \tag{1}$$
```
公众号平台
![image](https://github.com/user-attachments/assets/d9041c91-78a3-4452-a8aa-5f0431e01265)

安卓
![efe10b5465e175ae53ba85dbb3cd7ef](https://github.com/user-attachments/assets/c98356f8-804e-41be-bb87-104d17be9780)

IOS
![a98739efaa660449c9c165573cba76f](https://github.com/user-attachments/assets/0eeafba0-09fc-4044-8e4f-dee503abf326)

**Comment by yanglbme** [comment]
hi  @cangfengzhs

我们修复了这个问题，可以再试试看
