### ISSUE TITLE
公式显示不出来

### ISSUE THREAD

**Issue by ychuest** [doocs/md#384]
![image](https://github.com/user-attachments/assets/e2069278-1176-4804-b2e8-1c3b2ed960ee)
![image](https://github.com/user-attachments/assets/488cc5f6-b0e9-4246-9cf8-b7e44e2913d4)
我在https://doocs.github.io/md/上编辑好了，在网页的预先浏览部分能很好的显示，通过网页的发布，同步到微信公众号上，结果确公式乱码，要怎么解决嘞

**Comment by YangFong** [comment]
问题确实存在，涉及部分公式时，在公众号中会出现渲染异常。目前没有太好的解决方案，需要等待定位修复。

**Comment by ychuest** [comment]
希望后边能解决这个问题。这将是一款非常优秀的产品。

| |
湖南科技大学计算机学院杨城
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月05日 14:16 |
| 收件人 | doocs/md ***@***.***> |
| 抄送人 | Cheng ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [doocs/md] 公式显示不出来 (Issue #384) |

问题确实存在，涉及部分公式时，在公众号中会出现渲染异常。目前没有太好的解决方案，需要等待定位修复。

**Comment by yanglbme** [comment]
你好，发一下错乱的那些公式

**Comment by ychuest** [comment]
> 你好，发一下错乱的那些公式

$$
\mathcal{L}_{VQ} = \underbrace{\mathcal{L}_{CE}(X, \hat{X})}_{\mathcal{L}_{rec}} + \underbrace{\| \text{sg}[Z] - \tilde{Z} \|_2^2}_{\mathcal{L}_{code}} + \beta \underbrace{\| Z - \text{sg}[\tilde{Z}] \|_2^2}_{\mathcal{L}_{commit}}, \tag{4}
$$

**Comment by yanglbme** [comment]
hi @ychuest 

我们修复了这个问题，可以再试试看哈

**Comment by Achuan-2** [comment]
输入内容是这样就没法渲染
![PixPin_2024-09-24_12-25-16](https://github.com/user-attachments/assets/4a6b6e8e-ef93-4419-bde7-8743ffb64afb)
```
1. 样本量≥40，且理论频数T≥5时用卡方检验的基本公式

    $$
    \chi^2 = \sum \frac{(O - E)^2}{E}
    $$
2. 样本量≥40，但理论频数1≤T\<5时用卡方检验校正公式；

    美国统计学家F. Yates在1934年提出了一个计算卡方值的连续性校正公式

    $$
    \chi^2 = \sum \frac{(|O - E| - 0.5)^2}{E}
    $$

    其中，$O$ 是观测频数，$E$ 是期望频数，$0.5$ 是校正因子。这一校正减少了卡方统计量的值，降低了检验的偏向性，减少了假阳性结果的概率。
3. 若样本量\<40或理论频数T\<1时，需改用Fisher精确检验法进行统计分析。
```

**Comment by yanglbme** [comment]
![image](https://github.com/user-attachments/assets/d1b2f7e4-7b4e-4012-9c28-32fa9809f6ba)

目前如果是块级公式，需要打在行首 @Achuan-2

**Comment by Achuan-2** [comment]
> ![image](https://private-user-images.githubusercontent.com/21008209/370131457-d1b2f7e4-7b4e-4012-9c28-32fa9809f6ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNTMxMzEsIm5iZiI6MTcyNzE1MjgzMSwicGF0aCI6Ii8yMTAwODIwOS8zNzAxMzE0NTctZDFiMmY3ZTQtN2I0ZS00MDEyLTljMjgtMzJmYTk4MDlmNmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA0NDAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZjJjZjIyN2U5NjI4NTg0MjcxOWY1MTE0NmZkOWNiYTI0ZDEwOGZmNGZlNDNmMzc0YzQ3MTQ5YjdkMzMzMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._5oBQSFaxeJGf-V9gvLedZ4rX2K2eK2ME5bl6M0wu9U)
> 
> 目前如果是块级公式，需要打在行首 @Achuan-2
好的，不过能优化下吗，如果$$前面是tab键或空格，也可以渲染
