### ISSUE TITLE
保存草稿或发表后格式就变了

### ISSUE THREAD

**Issue by zxw1992** [doocs/md#387]
从网页复制到公众号编辑器时，格式都是保留下来的，而且是正确的。
但是发表后格式就完全变了，排版、字号、段落都会变，即使不发表，一点击“保存草稿”，也会变。
请问是什么原因？如何解决？

![Snip_2024-09-07_17-51-37](https://github.com/user-attachments/assets/88a427f3-2e1d-4d12-a9c2-6107441660f3)

**Comment by yanglbme** [comment]
必现吗，文档能不能贴一下？

**Comment by zxw1992** [comment]
> 必现吗，文档能不能贴一下？

每次都会出现。
文档下面这个：
[ai科研.md](https://github.com/user-attachments/files/16917470/ai.md)

**Comment by YangFong** [comment]
保存草稿时，平台会对其进行一定的整理，检查其中是否存在不合理的格式，所以效果要以保存后为准。

此外，我这边进行了本地测试，未发现变化之处，需要再补充一下问题。

![image](https://github.com/user-attachments/assets/29534d86-f7e4-4afc-af1b-f2248d66d136)

**Comment by zxw1992** [comment]
这个文档就是直接导出的，我也用的这个，复制过去就不行，问题会出在哪呢？

**Comment by yanglbme** [comment]
你好，浏览器用的是什么

**Comment by yanglbme** [comment]
然后有没有安装了一些插件，可能有影响

**Comment by zxw1992** [comment]
是浏览器插件的问题，我用在无痕模式关了所有插件试了下，就没这个问题了，但具体是哪个插件还不清楚。
非常感谢。

**Comment by yanglbme** [comment]
那这个先关闭了哈
