### ISSUE TITLE
建议：自定义css中加全局样式

### ISSUE THREAD

**Issue by mengkong6** [doocs/md#420]
1、自定义CSS中，缺少一个针对整个文档的属性，比如我想要文档整体的margin:10px 20px;无法操作
2、自定义的css能保存成主题不？

**Comment by YangFong** [comment]
1. 确实，当前并不支持对容器进行设置。
2. 自定义 css 方案会存储在浏览器中，你可以自行更名和在多个方案之间进行切换。而主题选项则是我们所预设的样式。
