### ISSUE TITLE
在Zeabur上部署进不去编辑界面

### ISSUE THREAD

**Issue by lijiajunply** [doocs/md#421]
我在Zeabur进行部署，但是发现不行
![image](https://github.com/user-attachments/assets/b1f35b54-106e-4c9a-adcf-71fda5c934f5)
| provider         │ nodejs                                             |
║───────────────────────────────────────────────────────────────────────|
║ packageManager   │ npm                                                ║
║───────────────────────────────────────────────────────────────────────║
║ framework        │ vite                                               ║
║───────────────────────────────────────────────────────────────────────║
║ nodeVersion      │ 20                                                 ║
║───────────────────────────────────────────────────────────────────────║
║ installCmd       │ COPY package.json* tsconfig.json* .npmrc* .        ║
║                  │ COPY package-lock.json* .                          ║
║                  │ RUN npm install                                    ║
║───────────────────────────────────────────────────────────────────────║
║ buildCmd         │ npm run build                                      ║
║───────────────────────────────────────────────────────────────────────║
║ outputDir        │ dist           |
然后就一直卡在初始界面，没有编辑页面

**Comment by yanglbme** [comment]
npm run build:h5-netlify

用这个试试

**Comment by yanglbme** [comment]
我知道了，Zeabur 似乎不支持指定 `npm run build:h5-netlify`。

有另一个解决办法，添加环境变量，Key = SERVER_ENV, Value = NETLIFY，然后重新部署，就可以了。

![image](https://github.com/user-attachments/assets/bfad98d0-a7c4-4730-b8f9-86cf4261073a)


我们项目已经部署成功了：

https://doocs-md.zeabur.app/
