### ISSUE TITLE
部署在vercel卡在启动页

### ISSUE THREAD

**Issue by Hanami1216** [doocs/md#422]
![image](https://github.com/user-attachments/assets/ed918d88-1cbb-4893-a87d-814e2d3cc48e)

**Comment by yanglbme** [comment]
同 #421 

看能不能使用 `npm run build:h5-netlify`，或者指定环境变量 Key = SERVER_ENV, Value = NETLIFY

**Comment by yanglbme** [comment]
试了，可以指定 npm run build:h5-netlify

以下是我尝试部署的结果：

https://mpmd.vercel.app/

**Comment by Hanami1216** [comment]
thanks!已解决
