### ISSUE TITLE
5级和6级标题无法使用了

### ISSUE THREAD

**Issue by Jerry-Freelancer** [doocs/md#428]
##### abc和###### abc 无法使用了

**Comment by YangFong** [comment]
并不是无法使用或语法不对，而是当前我们没有设置 5 级和 6 级的样式。

<img width="595" alt="image" src="https://github.com/user-attachments/assets/c9d5e512-575d-4650-b218-430b9398c856">

**Comment by Jerry-Freelancer** [comment]
您的邮件，我已接收。
