### ISSUE TITLE
格式化功能问题

### ISSUE THREAD

**Issue by F-Kapok** [doocs/md#434]
# 格式化后编辑区错乱，无法编辑
### 格式化前：
![9860168cc2fe78239a04effb05f11b6](https://github.com/user-attachments/assets/b77ed4f8-f06c-40a0-8294-90758c90fb7b)
### 格式化后：
![8888d800f3198d0bb1763855eb041d4](https://github.com/user-attachments/assets/a24c0c8a-c26b-40ce-bceb-0f907599c405)

**Comment by YangFong** [comment]
复现成功，大致可以定位到问题
