### ISSUE TITLE
代码块主题的显示无法改变

### ISSUE THREAD

**Issue by main-studio** [doocs/md#439]
改为其他的代码块主体，显示的效果始终是下面的样子：
![image](https://github.com/user-attachments/assets/c6f792f9-018e-4dc7-a867-6117ed84c656)

**Comment by YangFong** [comment]
两种可能：
- 代码块主题是使用的外部cdn，可能出现了失效的情况
- vpn网络连接被拒绝

**Comment by main-studio** [comment]
那需要怎么解决？我换了VPN的服务器或关掉VPN都不能改变显示的效果

**Comment by YangFong** [comment]
@main-studio 我这里是正常的，不能复现你的错误：

<img width="1319" alt="image" src="https://github.com/user-attachments/assets/b2eee5c0-0596-46e4-9629-666e9acd156e">

你需要试试换个浏览器，或是开隐私模式访问看看。

**Comment by main-studio** [comment]
我昨晚换浏览器试也是不行，刚刚开隐身模式显示可以随着设置正常变化，谢谢你，对了这是什么原因呀？

**Comment by YangFong** [comment]
主要就我前面所说的两个原因，浏览器不支持或被其他插件影响的倒不是很多，你开影身模式就正常了，也有一定可能是插件或缓存的问题。

这些主题资源是外部引入的，因为量比较多，就没有归并到项目中。
