### ISSUE TITLE
代码格式出现错位

### ISSUE THREAD

**Issue by ihengshuai** [doocs/md#443]
将格式化后的内容粘贴到官方的编辑器中，显示正常，如下图：

![image](https://github.com/user-attachments/assets/46c022df-f513-45bb-927f-8c53dd245ff6)

当预览文章时，样式发生异常：
![image](https://github.com/user-attachments/assets/e0089fd9-a150-44dd-a37a-872063008ddb)

**Comment by YangFong** [comment]
两个问题：

1. 需要提供可复现的文案。
2. 是否是粘贴后，点击保存，无异常，但点开测试链接，表现异常？

**Comment by ihengshuai** [comment]
> 两个问题：
> 
> 1. 需要提供可复现的文案。
> 2. 是否是粘贴后，点击保存，无异常，但点开测试链接，表现异常？

感谢回复，

1. 源代码：

在需要高亮的代码块的前一行及后一行使用三个反引号，同时**第一行反引号后面表示代码块所使用的语言**，如下：

```java
// FileName: HelloWorld.java
public class HelloWorld {
  // Java 入口程序，程序从此入口
  public static void main(String[] args) {
    System.out.println("Hello,World!"); // 向控制台打印一条语句
  }
}
```

2. 保存后，无异常，预览异常

**Comment by ihengshuai** [comment]
好像上周还没有问题，昨天开始有问题了，不知道是不是微信编辑器的格式化问题

**Comment by ihengshuai** [comment]
那应该没问题，可能我这么的隐形字符的问题。不过挺奇怪的，不管我是复制还是手写都会出现这问题  (ಥ﹏ಥ)

**Comment by ihengshuai** [comment]
发现在电脑上直接复制到 微信编辑器中 预览有问题。直接复制到手机app中的编辑器中 预览后没问题。。。
