### ISSUE TITLE
复制html到编辑器，再复制到微信公众号的编辑器，保存不了，提示“参数错误，.....”

### ISSUE THREAD

**Issue by hafung** [doocs/md#463]
如题

**Comment by yanglbme** [comment]
不支持从公众号到编辑器噢，编辑器需要写 Markdown 格式的文档

**Comment by hafung** [comment]
> 不支持从公众号到编辑器噢，编辑器需要写 Markdown 格式的文档

我是这样操作的，就是把已经写好的html 放编辑器里 然后点复制 再粘贴到微信的编辑器  -- 这样是不行的是么 只支持markdown的编写、复制是么。。

**Comment by yanglbme** [comment]
是的，目前只支持 markdown 文档渲染成 html

**Comment by hafung** [comment]
> 是的，目前只支持 markdown 文档渲染成 html

明白 （有计划支持么。。

**Comment by YangFong** [comment]
可见 #147，我是更推荐使用工具站点，完成大致的转换。如：https://d1tools.com/tools/convert-html-to-markdown/

<img width="1244" alt="image" src="https://github.com/user-attachments/assets/51255fcb-dfaa-4f01-9a0d-e93a7d9ad3b3">

**Comment by hafung** [comment]
> 可见 #147，我是更推荐使用工具站点，完成大致的转换。如：https://d1tools.com/tools/convert-html-to-markdown/
> 
> <img alt="image" width="1244" src="https://private-user-images.githubusercontent.com/70502828/394537784-51255fcb-dfaa-4f01-9a0d-e93a7d9ad3b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4ODgxMzgsIm5iZiI6MTczMzg4NzgzOCwicGF0aCI6Ii83MDUwMjgyOC8zOTQ1Mzc3ODQtNTEyNTVmY2ItZGZhYS00ZjAxLTlhMGQtZTkzYTdkOWFkM2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDAzMzAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMTYwOGE3NjA1ZTQ3NDYyZjgxOTM0MWI4NmY0ZTIyZmYzMzdlZGI3ODliYzU2OWNlMjUzYjExY2JkODQ0MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7ivXfTgLhYSGBWvHAx2te8nijJ2qqHYuXm01SmNPtes">

感谢推荐！ 这种工具将html转md后，行内css样式会丢失么？

**Comment by YangFong** [comment]
> 感谢推荐！ 这种工具将html转md后，行内css样式会丢失么？

我所想的使用方式是，将一段 HTML 转换成 Markdown 格式，然后复制到 md 编辑器当中，再复制到公众号发文编辑器当中。

如果你还要保留之前 HTML 的行内样式，和 md 编辑器合并，那是不行的，在转换过程中会丢失。

**Comment by YangFong** [comment]
需要完整迁移的话，那需要配合「自定义 CSS 」。
