### ISSUE TITLE
mermaid 的 流程图在微信显示有问题

### ISSUE THREAD

**Issue by outyua** [doocs/md#469]
<img width="1092" alt="image" src="https://github.com/user-attachments/assets/1eade80a-23f3-4b69-a8b9-205002564e6c" />
<img width="718" alt="image" src="https://github.com/user-attachments/assets/6f6917e1-a93c-490f-90c6-5905c630a067" />

mermaid 图的文字被截断了

**Comment by outyua** [comment]
找到问题了, 复制的时候, 在文字节点前增加了一个 P 标签, 占了一行, 把文字给顶下去了
<img width="562" alt="image" src="https://github.com/user-attachments/assets/4b58ff62-d9de-4721-963e-c2712611d0d5" />
编辑器预览的时候, 没有这个 p 标签, 复制之后粘贴到 微信公众号编辑器就有了

**Comment by YangFong** [comment]
很好的发现，等待确认一下，是复制之前就有该标签，还是复制之后生成，就能应对修复。

**Comment by yanglbme** [comment]
测试用例：

```mermaid
graph LR
    A[GraphCommand] --> B[update]
    A --> C[goto]
    A --> D[send]
    
    B --> B1[更新状态]
    C --> C1[流程控制]
    D --> D1[消息传递]
 ```

```mermaid
graph TD;
  A-->B;
  A-->C;
  B-->D;
  C-->D;
```

```mermaid
pie
  title Key elements in Product X
  "Calcium" : 42.96
  "Potassium" : 50.05
  "Magnesium" : 10.01
  "Iron" : 5
```

**Comment by yanglbme** [comment]
@outyua 目前应该可以了，可以再试试

**Comment by outyua** [comment]
修复了, 非常感谢
