### ISSUE TITLE
能否加上对Latex等数学公式的支持？

### ISSUE THREAD

**Issue by houcy** [doocs/md#49]
测试了一下不支持Latex语法，希望可以支持

$$ c = \sqrt{a^{2}+b_{xy}^{2} +e^{x}} $$

**Comment by yanglbme** [comment]
抽空开发中

**Comment by KnowsCount** [comment]
用一个 mathjax/katex 之类的吧。如果 @yanglbme 还没有开始，我可以来做做看。

**Comment by yanglbme** [comment]
> 用一个 mathjax/katex 之类的吧。如果 @yanglbme 还没有开始，我可以来做做看。

@KnowsCount 我还没开始做，欢迎贡献代码

**Comment by volksvagen** [comment]
@yanglbme 
另一个开源项目mark text已经有完整的LaTeX语法支持，是否可以考虑移植过来？
https://github.com/marktext/marktext

**Comment by jhrsya** [comment]
同求

**Comment by bravekingzhang** [comment]
你们说的是这个？
<img width="1005" alt="image" src="https://github.com/doocs/md/assets/4476322/ce7ec4d4-faa8-423f-bd98-99d7329d0aed">

**Comment by volksvagen** [comment]
对，没错，像Typora那种实时的公式渲染体验
