### ISSUE TITLE
数字的幂，粘贴到公众号保存后上标变下表

### ISSUE THREAD

**Issue by coding-w** [doocs/md#490]
-10<sup>9</sup> <= nums[i] <= 10<sup>9</sup>
粘贴到公众号截图如下：
<img width="214" alt="image" src="https://github.com/user-attachments/assets/6aa55365-6f2d-4505-97a9-949a5d115a94" />
保存之后
<img width="1458" alt="image" src="https://github.com/user-attachments/assets/f1f853fe-eeab-4df3-8535-c5e5170a7e16" />

**Comment by yanglbme** [comment]
用 LATEX 语法试试：

```
这是行内公式 $-10^9 \leq nums[i] \leq 10^9$


这是块公式：

$$
-10^9 \leq nums[i] \leq 10^9
$$

两种效果
```

**Comment by coding-w** [comment]
这样是可行的，有一个特俗情况会导致复制失败，如下

```
$-10^9 \leq nums[i] \leq 10^9$

$$
-10^9 \leq nums[i] \leq 10^9
$$

公式前没有其他字符，如"这是行内公式 "，就无法将公式粘贴到公众号中
```

**Comment by yanglbme** [comment]
![image](https://github.com/user-attachments/assets/4a39ad5f-2be0-48b6-b197-fdd6db31b78d)

这种情况吗，我这里没问题

**Comment by yanglbme** [comment]
噢，应该是公式后没有其他字符，会有问题

**Comment by yanglbme** [comment]
> 这样是可行的，有一个特俗情况会导致复制失败，如下
> 
> ```
> $-10^9 \leq nums[i] \leq 10^9$
> 
> $$
> -10^9 \leq nums[i] \leq 10^9
> $$
> 
> 公式前没有其他字符，如"这是行内公式 "，就无法将公式粘贴到公众号中
> ```

@coding-w 这个问题再试试看，我改了下
