### ISSUE TITLE
有序序列下的代码块的格式问题

### ISSUE THREAD

**Issue by coding-w** [doocs/md#494]
有序序列下，缩进后的代码块第一行格式有问题
<img width="1312" alt="image" src="https://github.com/user-attachments/assets/4bb687dd-75fd-4e1f-85d9-8d631f327f25" />
在有缩进的代码块，空出代码块的第一行，后续代码无问题

**Comment by yanglbme** [comment]
把你的文本发出来，我们看看

**Comment by yanglbme** [comment]
我这里正常：

![image](https://github.com/user-attachments/assets/6fde86fa-a4ce-41a5-9083-20d14ce305e9)

**Comment by coding-w** [comment]
https://md.randbox.top/

这个是你们运维的吗，我之前用的是这一个....
