### ISSUE TITLE
Who's using doocs/md? | 有哪些公众号在使用 doocs/md 进行排版？

### ISSUE THREAD

**Issue by yanglbme** [doocs/md#5]
各位朋友，你们好。

如果你们使用 [doocs/md](https://github.com/doocs/md) 工具进行图文排版，欢迎在下方留言。后续我考虑在 README 首页中展示你们的公众号。谢谢你们 :D

**Comment by yanglbme** [comment]
## 公众号
Doocs开源社区

## Logo
![image](https://user-images.githubusercontent.com/21008209/71453045-50269300-27c4-11ea-835d-084439d17d72.png)

## 示例文章
[阿里又一个 20k+ stars 开源项目诞生，恭喜 fastjson！](https://mp.weixin.qq.com/s/RNKDCK2KoyeuMeEs6GUrow)

**Comment by AlainOUYANG** [comment]
## 公众号
TheAIchemist
## Logo
![WechatIMG160](https://user-images.githubusercontent.com/22619010/72618127-bec9bd00-393a-11ea-92f7-36d310837b94.jpeg)

**Comment by juemuren4449** [comment]
# 公众号

掘墓人的小铲子

# Logo

![掘墓人的小铲子](https://img.juemuren4449.com/7af8125993c702dcffbd99ade00c90b4.png)

# 二维码

![掘墓人的小铲子](https://img.juemuren4449.com/2c867b6c99c5da99399ae1b13bb0ed41.jpg)

# 文章

[一文多发神器--ArtiPub&OpenWrite](https://mp.weixin.qq.com/s/FpGIX9viQR6Z9iSCEPH86g)

[iShot--macOS上最好用的截图工具](https://mp.weixin.qq.com/s/ItMdc67XSKXv54Ou9EUFEA)

[CSDN文章数据导出工具](https://mp.weixin.qq.com/s/TMD7h3foHPFFANpMnn2QQg)

[助力社区疫情防控--智慧e通行](https://mp.weixin.qq.com/s/xX3pEcXBqt9eOG-nyZA1cA)

[对微信部分改进的看法](https://mp.weixin.qq.com/s/7WQhzm61DIMUVy2-a9yn2g)

**Comment by yanglbme** [comment]
@juemuren4449 谢谢反馈，已添加。

**Comment by lijianqiang** [comment]
# 公众号
全网重点

# logo
![logo256](https://user-images.githubusercontent.com/1551302/76947459-9e20e200-6940-11ea-9c48-258c00714c13.jpg)

# 二维码
![share](https://user-images.githubusercontent.com/1551302/76947663-eb9d4f00-6940-11ea-9012-5ae7025655e3.jpg)

# 其他
提取了MD样式，改写成了一份简易Java版本
示例文章：
https://mp.weixin.qq.com/s/yB3ZH3jmcF_LbzuKmnR9BQ

**Comment by yanglbme** [comment]
@lijianqiang 谢谢支持，已添加。

**Comment by robin4han** [comment]
非常感谢好用的工具。省了好多麻烦。
公众号：**土嗨英语**。
![](https://imgkr.cn-bj.ufileos.com/ee059954-c887-4fa5-adda-a20a5d66b0fc.jpg)

**Comment by yanglbme** [comment]
@robin4han 没看到使用 doocs/md 排版的相关文章。

**Comment by Weixinxin1994** [comment]
### 公众号:
爱码士的内心独白
### Logo
![image](https://user-images.githubusercontent.com/26537465/77853986-082b6800-721a-11ea-90c6-124cb8d1f9a7.png)
## 示例文章
- [死磕JavaScript系列之原来你是对象(一)](https://mp.weixin.qq.com/s?__biz=Mzg5MDA2NzM0Mw==&mid=2247483700&idx=1&sn=e91063d1373b95d9d22722b98b23b1e7&chksm=cfe301d4f89488c29978cc7f907e8b00079b6c68a7586f70a70d71e40919de5226cc5fa88e8a&token=235392371&lang=zh_CN&scene=21#wechat_redirect)
- [死磕JavaScript系列之对象的原型(二)](https://mp.weixin.qq.com/s?__biz=Mzg5MDA2NzM0Mw==&mid=2247483704&idx=1&sn=a148f12ef5c95ab3afa7e3acade4f3d6&chksm=cfe301d8f89488ce7ef527ca5bded55aa7afd6652eee5900fd4daa07be2c3ab18185fb3dbb85&token=1560817753&lang=zh_CN&scene=21#wechat_redirect)
- [死磕JavaScript系列之对象的hasOwnProperty函数(三)](https://mp.weixin.qq.com/s?__biz=Mzg5MDA2NzM0Mw==&mid=2247483708&idx=1&sn=33c60cb079c7a08628436fcd20c51715&chksm=cfe301dcf89488ca167405e45e50bad49a2cc48dec64729203420efa949e934e6c216dd6550e&token=278113369&lang=zh_CN&scene=21#wechat_redirect)

ps: 谢谢大佬,审美很相似,我基本所有文章都是用的这个.

**Comment by yanglbme** [comment]
@Weixinxin1994 谢谢使用，已添加。

**Comment by wll8** [comment]
使用了不少 markdown 的应用及样式。要么就是生成的效果公众号不支持；要么就是样式不满意；总有些这样那样的小问题。

感谢作者提供这么好用的工具，为微信文章而定制的 markdown ，后续也会多使用这个工具，以及推荐给朋友，希望有机会为优秀的工具添砖添瓦。

# 公众号
乐玩nodejs npm工具库

## LOGO
![乐玩nodejs npm工具库](https://user-images.githubusercontent.com/28223260/78350244-7172f880-75d7-11ea-9f54-e091b7e421f1.jpg)

## 二维码
![乐玩nodejs npm工具库](https://user-images.githubusercontent.com/28223260/78349538-56ec4f80-75d6-11ea-8c8f-44ce66d7f96d.jpg)

## 示例文章
[Quick Start - 天下武功，唯快不破！效率工具，老少皆宜](https://mp.weixin.qq.com/s?__biz=MzIzNTUzNDQ3MA==&mid=2247483749&idx=1&sn=5d7e06bd5331bcf11b288c2b59f356db&chksm=e8e4e08cdf93699a48497faab1e8dc144de9e348299fb8b76e527e583ed4d257073a25c6f642&token=1677569563&lang=zh_CN#rd)

**Comment by yanglbme** [comment]
@wll8 感谢支持，已添加。

**Comment by simowce** [comment]
感谢提供这个非常好用的工具，markdown 用户的福音：

# 公众号

![][0]

# 示例文章

[全网首发！GPU 驱动自升级原理详解][1]

  [0]: http://static.zybuluo.com/simowce/lvppugibwj755w7nsttdt4eo/qrcode_for_gh_58107b171ae0_258.jpg
  [1]: https://mp.weixin.qq.com/s?__biz=MzI5NzExMDYwNQ==&mid=2664435647&idx=1&sn=3c16fc67608f3b73c1febf803e2e752a&chksm=f79eb29dc0e93b8b02a1c7e73660d355ea3427816a519efcf1773e3d58a745eaa06a76b0debd&token=22044436&lang=zh_CN#rd

**Comment by yanglbme** [comment]
@simowce 感谢使用，已经添加到首页。

**Comment by XUJINPENGSIR** [comment]
公众号：鹏哥的世界

 ![](https://imgkr.cn-bj.ufileos.com/d6c85cbb-d99c-4d88-aaa3-bfe31c111bb8.gif)

**Comment by XUJINPENGSIR** [comment]
公众号：鹏哥的世界

 
![qrcode_for_gh_bfadfb616b69_258](https://user-images.githubusercontent.com/49874785/81470518-b7962a00-921d-11ea-884c-1a0ffdae4a4a.jpg)

**Comment by zhaoolee** [comment]
公众号 「0加1」

![qrcode_for_gh_cffef2fcf693_258](https://user-images.githubusercontent.com/15868458/81516279-f0431a00-9369-11ea-97bb-769e4a4dd1bf.jpg)


感谢这个工具，每天都用～

示例文章: [不限速下载bilibili壁纸娘的432张壁纸](https://mp.weixin.qq.com/s/qefHCmToAdowBz2JwBn_ug)

**Comment by yanglbme** [comment]
@zhaoolee 谢谢使用，已添加。

**Comment by gao2ming** [comment]
## 公众号
好酸一柠檬（ID: OneBadLemon）
## Logo
![lemon](https://user-images.githubusercontent.com/47825352/87085605-be174100-c262-11ea-91cb-7f374936aa06.jpeg)
## 二维码
![lemonbad](https://user-images.githubusercontent.com/47825352/87085351-5103ab80-c262-11ea-8f77-9d059b235766.jpg)
## 示例文章
[阅读计划 | 传记、社科类](https://mp.weixin.qq.com/s/CVqmcu_OGG8TQO4FViAQ3w)

**Comment by YuJian95** [comment]
# 感谢

很好用的一款编辑器。

## 公众号

编程图解

## logo

![image](https://user-images.githubusercontent.com/37510077/94440352-33484180-01d4-11eb-9d25-8fce3505cbfa.png)


## 二维码

![image](https://user-images.githubusercontent.com/37510077/94440419-44914e00-01d4-11eb-8b16-a04b3c29c033.png)


## 示例

[Object 对象之母](https://mp.weixin.qq.com/s?__biz=MzIwODk0NzcwMQ==&mid=2247483754&idx=1&sn=a218aebe9d99aafe0b7e730cd250799a&chksm=977a11f0a00d98e691a5f9f00706702d3d57e27e0852c3b9576e5b2a07ea6136d308d97b1f11&scene=126&sessionid=1601300493&key=56c1a4d5743468c980164ce2407d24dace6e1a58b4be30058e53b461cbc41898a5cd706fb7556a48a1cb572daa4003dab61c72f7494bb55f5f34709d6ea1cec80f1192934cd2e5df1f75a9c76f7ab40fb592d17d03c4709e2f4cf012ffb9e396102d43d76924d2a3c36214c1f0d8d295c5aa793868feac19b0e0ad03ee86d794&ascene=1&uin=MTE3ODg2Mjg2NA%3D%3D&devicetype=Windows+10+x64&version=62090529&lang=zh_CN&exportkey=A2vuw6uL7rJRIz6kIL1zBKQ%3D&pass_ticket=NLn7nNRM2cFaJXiisNbQW6XRhfXAUxViFJIksYY5WBHkCH1OSiZ8u0hOZsnN9ALX&wx_header=0)

**Comment by yanglbme** [comment]
@YuJian95 已添加，欢迎继续使用
