### ISSUE TITLE
能否做成npm包发布

### ISSUE THREAD

**Issue by sysBlackFox** [doocs/md#52]
现在想在项目里引入这个，太麻烦了，还得扣代码，也不利于后期的升级与维护。

**Comment by LetHergo** [comment]
看了下 使用方式都没有写。

**Comment by secreter** [comment]
+1

**Comment by sinboun** [comment]
+1

**Comment by wll8** [comment]
@sysBlackFox 你希望能在项目里如何引用？效果是什么？

**Comment by wll8** [comment]
现在我们支持直接使用 npm 生成私人服务，欢迎使用。
![image](https://user-images.githubusercontent.com/28223260/143765611-beff0cbc-8876-4550-b9fd-2d3905a512f3.png)

``` sh
# 安装
npm i -g @doocs/md-cli

# 启动
md-cli

# 访问
open http://127.0.0.1:8800/md/
```
