### ISSUE TITLE
代码块乱了

### ISSUE THREAD

**Issue by kricewd** [doocs/md#57]
![image](https://user-images.githubusercontent.com/17675920/109419903-c2b78200-7a0a-11eb-87fc-c34b900c3498.png)

**Comment by yanglbme** [comment]
@kricewd 今天发了个版本，出了 bug，我们会尽快解决，谢谢反馈。

**Comment by JimQing** [comment]
代码块样式问题已经修复了，清空缓存重新访问即可恢复正常，希望不会造成你的困扰，如有其他问题欢迎提issue，我们将在第一时间为你处理。
