### ISSUE TITLE
裂墙需求便携式离线版~~~

### ISSUE THREAD

**Issue by hitboysurelee** [doocs/md#61]
单位电脑不能上网, 只能用离线的绿色版本...超级喜欢这种自定义样式的模式, 能不能出一个单机的离线便携版呀, 我日常办公已经离不开Markdown了

**Comment by yanglbme** [comment]
目前可以将 doocs/md 项目 clone 到本地，然后 build 构建后运行。

不过离线版的话，图片上传是个问题。

**Comment by KnowsCount** [comment]
我马上提个 pwa 的 pr 看看。

**Comment by KnowsCount** [comment]
下载离线版（dmg）👇：
https://drive.knowscount.cc/s/p9Id

**Comment by hitboysurelee** [comment]
> 下载离线版（dmg）👇：
> https://drive.knowscount.cc/s/p9Id

有win版嘛?

**Comment by KnowsCount** [comment]
> > 下载离线版（dmg）👇：
> > https://drive.knowscount.cc/s/p9Id
> 
> 有win版嘛?

@hitboysurelee 目前没有，再给我点时间。

**Comment by hitboysurelee** [comment]
> > > 下载离线版（dmg）👇：[https](https://drive.knowscount.cc/s/p9Id) : 
> > > [//drive.knowscount.cc/s/p9Id](https://drive.knowscount.cc/s/p9Id)
> > 
> > 
> > 有win版嘛？
> 
> @hitboysurelee目前没有，再给我点时间。
> 
> 能否要一个联系方式？-我借你windows一用。

> Github没有私信, 留下自己联系方式大家都能看到很蛋疼,当然, 可能我是小白, 有别的方法可能我不知道

**Comment by KnowsCount** [comment]
@hitboysurelee 有了。来这里下——https://knowscount.github.io/md-website/。

**Comment by hitboysurelee** [comment]
> @hitboysurelee 有了。来这里下——https://knowscount.github.io/md-website/ 。

感谢, 帮了大忙了, 已"投币"支持
