### ISSUE TITLE
代码块建议

### ISSUE THREAD

**Issue by TRHX** [doocs/md#75]
1、建议内置几套不同代码块样式，参考另一个编辑器：https://markdown.com.cn/editor/
2、代码有换行，但是复制到公众号就没有换行了，显得不太美观，如下图所示：
![Snipaste_2021-11-04_15-58-54.png](https://i.loli.net/2021/11/04/zFKOAC1yHBwagZI.png)

**Comment by yanglbme** [comment]
好的，问题已收到，我们看看怎么处理

**Comment by yanglbme** [comment]
@TRHX 代码块换行问题应该是修复了

**Comment by TRHX** [comment]
> @TRHX 代码块换行问题应该是修复了

谢谢，我这边测试也正常了

**Comment by miaogaolin** [comment]
> @TRHX 代码块换行问题应该是修复了

代码块我想有更多的选择，目前咱的代码是没有的，所以我等不及了，代码就改用了 hightlight.js。
也不知道我这种做法是否符合作者的想法，所以不知道是否可以 pr。

代码地址：https://github.com/miaogaolin/md

在线编辑器：https://printlove.cn/md/

**Comment by TRHX** [comment]
> > @TRHX 代码块换行问题应该是修复了
> 
> 代码块我想有更多的选择，目前咱的代码是没有的，所以我等不及了，代码就改用了 hightlight.js。 也不知道我这种做法是否符合作者的想法，所以不知道是否可以 pr。
> 
> 代码地址：https://github.com/miaogaolin/md
> 
> 在线编辑器：https://printlove.cn/md/

感觉不错，如果能再加个行号就更6了（手动狗头）

**Comment by miaogaolin** [comment]
> 

那下来我安排上

**Comment by yanglbme** [comment]
样式上需要做调整：

![309959d5280462e169f57cbfa1dc1a5](https://user-images.githubusercontent.com/21008209/143376852-fb15e48d-f229-4289-8534-e34dd140e212.jpg)

---

以下是目前线上的代码块效果，支持代码滑动：

![67824fb748630c82d2c62bcb72c4b09](https://user-images.githubusercontent.com/21008209/143376871-aa59f29a-7541-41e9-98c4-d59e2f4c00bd.jpg)

**Comment by miaogaolin** [comment]
> 样式上需要做调整：
> 
> ![309959d5280462e169f57cbfa1dc1a5](https://user-images.githubusercontent.com/21008209/143376852-fb15e48d-f229-4289-8534-e34dd140e212.jpg)
> 
> 以下是目前线上的代码块效果，支持代码滑动：
> 
> ![67824fb748630c82d2c62bcb72c4b09](https://user-images.githubusercontent.com/21008209/143376871-aa59f29a-7541-41e9-98c4-d59e2f4c00bd.jpg)

下来我再细调整下，目前我改后有 4 个点不一样：
1. 代码块没有和主题内容对其（个人其实喜欢这种），不过为了统一我还是改下
2. 代码块圆角
3. 代码块滑动
4. highlight.js 11.3.1 的 github 样式背景是白色

**Comment by yanglbme** [comment]
白底不太好看，代码块颜色最好与背景做一点区分 @miaogaolin

**Comment by miaogaolin** [comment]
> 白底不太好看，代码块颜色最好与背景做一点区分 @miaogaolin

是不好，我还在考虑，毕竟这是 hightlight.js 11.3.1 自带的 github 样式

**Comment by miaogaolin** [comment]
> 白底不太好看，代码块颜色最好与背景做一点区分 @miaogaolin

在看看 https://printlove.cn/md/，看有啥问题。

我改的东西比较多，例如：
* 把之前的一套代码主题都删除了
* 微信代码块滑动逻辑改了，删除了一些代码
* 还有滚动时，有个 bug，也修复了

**Comment by yanglbme** [comment]
代码块字体字号和间距感觉总体上偏大了一点，这个可以调整吗？


![f3060cb9d2bb833229287c116b2f64f](https://user-images.githubusercontent.com/21008209/143560197-d864d575-10fc-4f3d-b961-91e6f0702425.jpg)

**Comment by yanglbme** [comment]
另外，导出 HTML 页面，报错了

**Comment by miaogaolin** [comment]
> 代码块字体字号和间距感觉总体上偏大了一点，这个可以调整吗？
> 
> ![f3060cb9d2bb833229287c116b2f64f](https://user-images.githubusercontent.com/21008209/143560197-d864d575-10fc-4f3d-b961-91e6f0702425.jpg)

哈哈哈哈，我看着小，故意调大了

**Comment by yanglbme** [comment]
好，那字体保持你那样吧

**Comment by miaogaolin** [comment]
> 好，那字体保持你那样吧

那我好好测一遍，改的太多，影响到别的了

**Comment by yanglbme** [comment]
@miaogaolin 有个小问题，重置页面内容、样式的时候，实际上样式已经重置，但顶部代码块选项卡还是处于选中其他选项的状态。

![image](https://user-images.githubusercontent.com/21008209/143596416-e4e3db7c-2b23-4876-8a4b-7318f9ac3d69.png)

**Comment by miaogaolin** [comment]
> https://printlove.cn/md/

[https://printlove.cn/md/](https://printlove.cn/md/) 再看看还有啥问题

**Comment by yanglbme** [comment]
@miaogaolin 没啥问题，可以提个 pr
