### ISSUE TITLE
外链 不能展示

### ISSUE THREAD

**Issue by Hatcat123** [doocs/md#8]
在markdown中写的外链，在您平台上转化个时候，丢失了跳转的外链。有解决的办法吗？

**Comment by Hatcat123** [comment]
sorry！已经验证了，可以展示。是我的疏忽

**Comment by yanglbme** [comment]
好的，外链在微信图文无法直接展示，所以这个编辑器默认采取了跟微信同样的处理方式：直接丢掉外链。如果需要保留，可打开顶部开关，会自动将外链追加到文末。

**Comment by Hatcat123** [comment]
这真是一个非常优秀的编辑器。清爽的排版让我看着很舒服！大赞
