### ISSUE TITLE
编辑器底部经常出现无法完全展示的情况，被隐藏了几行

### ISSUE THREAD

**Issue by wmlc** [doocs/md#85]
![QQ20211110-111204](https://user-images.githubusercontent.com/12483202/141042927-9f610d64-4658-4880-83a4-0cc178496968.png)

往下拉也拉不动

**Comment by yanglbme** [comment]
@wmlc 确实有这个问题，我们看看怎么处理

**Comment by yanglbme** [comment]
@wmlc 你好，已修复

**Comment by wmlc** [comment]
![image](https://user-images.githubusercontent.com/12483202/141794555-e503f0ae-ac96-4aaa-9566-7c2884a3e4aa.png)

测试了下  还是不行

**Comment by yanglbme** [comment]
无法定位到最后一行吗？

**Comment by yanglbme** [comment]
清下缓存试试？

**Comment by wmlc** [comment]
左边参考文档底下  还有一行   显示不出来

**Comment by yanglbme** [comment]
我待会确认一下，你本地环境是什么？浏览器、操作系统

**Comment by wmlc** [comment]
mac   chrome

你用这个markdown文档试试  http://maojiezhenxuan.oss-cn-qingdao.aliyuncs.com/content.md

**Comment by yanglbme** [comment]
@wmlc 再刷新浏览器试试？

**Comment by yanglbme** [comment]
麻烦确认一下哈 @wmlc

**Comment by wmlc** [comment]
可以了

**Comment by wmlc** [comment]
辛苦了
