### ISSUE TITLE
图片上传报错

### ISSUE THREAD

**Issue by lanhudong** [doocs/md#86]
![1345](https://user-images.githubusercontent.com/83766345/142182511-cbe68bd3-3406-4590-a94d-e77ac4087764.png)
作者您好，发现在使用过程中，使用默认图床上传图片，会出现错误。图片是上传成功的，但是并没有把上传后的链接填充到编辑区域。

**Comment by yanglbme** [comment]
好像确实有这个问题，我们查一下

**Comment by yanglbme** [comment]
@lanhudong 图片上传的结果数据，格式上有所调整，已处理

**Comment by yanglbme** [comment]
已经修复了，这个 issue 我们先关闭了哈
