### ISSUE TITLE
求 LaTeX 支持！

### ISSUE THREAD

**Issue by AlainOUYANG** [doocs/md#9]
有没有可能会支持 LaTeX 呀？现在每次都只能先发在知乎上，再把知乎生成的图片复制粘贴到公众号上。。

**Comment by yanglbme** [comment]
@AlainOUYANG 你好，目前正在分支上全面改造项目，之后会支持 LaTex

**Comment by xindoo** [comment]
> @AlainOUYANG 你好，目前正在分支上全面改造项目，之后会支持 LaTex

何时上线？
